### ISSUE TITLE
gradle 5

### ISSUE THREAD

**Issue by dhakehurst** [korlibs/korui#2]
will you be upgrading to gradle 5 ?

I'm getting "Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only."

**Comment by soywiz** [comment]
Yeah I'm aware of that issue.
Check this thread: https://github.com/korlibs/klock/issues/16

With Kotlin 1.3.20 I will be able to use Gradle 5. And I will definitely use it.

**Comment by soywiz** [comment]
Done
